paths:
  data: _data
  collections: ''
  layouts: _includes
  static: ''
  uploads: uploads
  includes: _includes
  pages: ''
collections_config: {}
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
timezone: Etc/UTC
